# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Test dev container feature

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - deploy/devcontainer-feature/**
      - .github/workflows/devcontainer-feature-test.yaml
    branches:
      - main
  workflow_call:

permissions: {} # disable permissions

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        baseImage:
          - mcr.microsoft.com/devcontainers/base:ubuntu
          - mcr.microsoft.com/devcontainers/base:debian
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Generating tests for Radius CLI (default) against '${{ matrix.baseImage }}'
        run: devcontainer features test --skip-scenarios -f radcli -i ${{ matrix.baseImage }} .
        working-directory: ./deploy/devcontainer-feature

  test-scenarios:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Generating tests for radcli scenarios
        run: devcontainer features test -f radcli --skip-autogenerated --skip-duplicated .
        working-directory: ./deploy/devcontainer-feature
