# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Validate devcontainer-feature.json files
on:
  workflow_dispatch:
  #pull_request:
  #  paths:
  #    - "deploy/devcontainer-feature/**"
  #    - ".github/workflows/devcontainer-feature-test.yaml"
  #  branches:
  #    - main

permissions: {} # disable permissions

jobs:
  validate:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          validate-only: "true"
          base-path-to-features: ./deploy/devcontainer-feature/src
